// <auto-generated />
using System;
using CollegeSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollegeSystem.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CollegeSystem.Models.AcademicDay", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("scheduleID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("scheduleID");

                    b.ToTable("days");
                });

            modelBuilder.Entity("CollegeSystem.Models.Schedule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("schedules");
                });

            modelBuilder.Entity("CollegeSystem.Models.StudentSubject", b =>
                {
                    b.Property<int>("studentID")
                        .HasColumnType("int");

                    b.Property<int>("subjectID")
                        .HasColumnType("int");

                    b.HasKey("studentID", "subjectID");

                    b.HasIndex("subjectID");

                    b.ToTable("studentSubjects");
                });

            modelBuilder.Entity("CollegeSystem.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AcademicDayid")
                        .HasColumnType("int");

                    b.Property<int>("academicYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("examDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("lectureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcademicDayid");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("CollegeSystem.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime?>("Createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("age")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("CollegeSystem.Models.Student", b =>
                {
                    b.HasBaseType("CollegeSystem.Models.User");

                    b.Property<int>("academicYear")
                        .HasColumnType("int");

                    b.Property<int>("classNumber")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("CollegeSystem.Models.AcademicDay", b =>
                {
                    b.HasOne("CollegeSystem.Models.Schedule", null)
                        .WithMany("days")
                        .HasForeignKey("scheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollegeSystem.Models.StudentSubject", b =>
                {
                    b.HasOne("CollegeSystem.Models.Student", "Student")
                        .WithMany("subjects")
                        .HasForeignKey("studentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollegeSystem.Models.Subject", "Subject")
                        .WithMany("students")
                        .HasForeignKey("subjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("CollegeSystem.Models.Subject", b =>
                {
                    b.HasOne("CollegeSystem.Models.AcademicDay", null)
                        .WithMany("subjects")
                        .HasForeignKey("AcademicDayid");
                });

            modelBuilder.Entity("CollegeSystem.Models.AcademicDay", b =>
                {
                    b.Navigation("subjects");
                });

            modelBuilder.Entity("CollegeSystem.Models.Schedule", b =>
                {
                    b.Navigation("days");
                });

            modelBuilder.Entity("CollegeSystem.Models.Subject", b =>
                {
                    b.Navigation("students");
                });

            modelBuilder.Entity("CollegeSystem.Models.Student", b =>
                {
                    b.Navigation("subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
